# https://docs.mitmproxy.org/stable/concepts-modes/#socks-proxy

x-mitmdump: &mitmdump
  image: mitmproxy/mitmproxy:9.0.1
  init: true

services:
  proxy:
    <<: *mitmdump
    command:
      - mitmdump
      - --server
      - --mode
      - socks5
      - --listen-host
      - 0.0.0.0
      - --listen-port
      - "2000"
      - --set
      - stream_large_bodies=8m
      - --save-stream-file
      - "+/data/%Y-%m-%d.flows"
    volumes:
      # 只给一个容器开放写权限，确保所有proxy共用相同的配置
      - ./conf:/home/mitmproxy/.mitmproxy
      - ./data:/data
